version: '2'
services:
  redis:
    image: redis:latest
    restart: always
  vstup:
    build: .
    command: bash -c "cd /code/src && python main.py "
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - redis